### ISSUE TITLE
Fix the Header

### ISSUE THREAD

**Issue by khwa04** [vishanurag/Canvas-Editor#928] opened 2024-10-25 11:09 UTC
![image](https://github.com/user-attachments/assets/a6f1b116-33e3-4f5d-901e-d45ffbe9d85c)
 I wish to fix the Header Column.
Please assign this issue to me under gssoc extnd and Hacktoberfest.

**Comment by vishanurag** [comment] 2024-10-25 15:44
The issue is already fixed by someone else

**Closed by vishanurag** 2024-10-25 15:44 UTC
