### ISSUE TITLE
Multiple Instances of Code showing in ui of the Website

### ISSUE THREAD

**Issue by itsHarsh2** [vishanurag/Canvas-Editor#1000] opened 2024-10-27 19:43 UTC
DESCRIPTION :

I have noticed that certain code snippets appear multiple times throughout the GSSoC website, including at the end of the site and in the middle of various sections. This redundancy can lead to maintenance challenges and negatively impact the overall performance and design consistency of the website.

 BEHAVIOUR :

1. The same UI code appears in multiple locations, which can result in inconsistencies in appearance and functionality.
2.This duplication may complicate updates and maintenance, making it harder to ensure uniformity across the site.

![WhatsApp Image 2024-10-28 at 01 11 34_6580b54d](https://github.com/user-attachments/assets/f02deea5-0a81-4acf-b5eb-896e766af113)

**Comment by vishanurag** [comment] 2024-10-28 07:20
The issue is already assigned to someone else

**Closed by vishanurag** 2024-10-28 07:20 UTC
